repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: ["--fix"]  # keep in sync with verify
      - id: ruff-format

  # Optional: enable Black if you prefer it in addition to ruff-format
  # - repo: https://github.com/psf/black
  #   rev: 24.8.0
  #   hooks:
  #     - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies: []
        args: ["-p", "example_pkg"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json

  # Optional: enable codespell to catch typos in code/docs
  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.3.0
  #   hooks:
  #     - id: codespell
  #       args: ["--ignore-words-list=crate,ba"]
